#!/usr/bin/env php
<?php
require $_SERVER["PWD"] . '/vendor/autoload.php';
use Cart\Commands\MigrateCommand;
use Cart\Commands\MigrateRollbackCommand;
use Cart\Commands\MigrateLaravelCommand;
use Symfony\Component\Console\Formatter\OutputFormatterStyle;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;
use Cart\Kernel;
use Symfony\Component\Console\Application;


(new Kernel())->bootstrapping();
$application = new Application();
$application->add(new MigrateCommand());
$application->add(new MigrateRollbackCommand());
$application->add(new MigrateLaravelCommand(new OutputFormatterStyle('black', 'yellow', array('bold', 'blink')) , new ProgressBar( new ConsoleOutput, 2)) );
$application->run();